**IMPORTING LIBRARIES**

In [1]:
import bs4 as bs
import urllib.request
import re

**SCRAPING THE WEBSITE DATA**

In [2]:
scraped_data = urllib.request.urlopen('https://www.brookings.edu/research/what-is-artificial-intelligence/')
#scraped_data = urllib.request.urlopen('https://news.mit.edu/2023/improving-machine-learning-models-reliability-0213')

article = scraped_data.read()

parsed_article = bs.BeautifulSoup(article,'lxml')

paragraphs = parsed_article.find_all('p')

article_text = ""

for p in paragraphs:
    article_text += p.text

In [3]:
print(len(article_text))

11752


In [4]:
#from google.colab import drive
#drive.mount('/content/drive')

**IMPORTING NLTK LIBRARY**

In [5]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

**DATA PREPROCESSING**

In [6]:
from nltk.tokenize import word_tokenize

def remove_shortWord(sentences):
  remove_word={"he's":"he is","she's":"she is","that's":"that is","i'm":"i am","what's":"what is","where's":"where is","\'ll":"will","\'ve":"have","\'re":"are","\'d":"would","won't":"would not","willn't":"will not","can't":"can not","don't":"do not"}
  words=sentences.split()
  for i in range(len(words)):
    if words[i] in set(remove_word.keys()):
      words[i]=remove_word[words[i]]
  words=" ".join(words)
  return words

In [7]:
from nltk.tokenize import sent_tokenize,word_tokenize
import regex

def tokenize_sentence(article_text):
  sents=sent_tokenize(article_text) 
  sent_list=[]
  for sent in sents:
    sent=sent.strip()
    sent=sent.lower()
    sent=remove_shortWord(sent) 
    sent_list.append(sent)
  return(sent_list)


sentences=tokenize_sentence(article_text)
sent_for_print=sentences
print(sentences)

['this report is part of "a blueprint for the future of ai," a series from the brookings institution that analyzes the new challenges and potential policy solutions introduced by artificial intelligence and other emerging technologies.few concepts are as poorly understood as artificial intelligence.', 'opinion surveys show that even top business leaders lack a detailed sense of ai and that many ordinary people confuse it with super-powered robots or hyper-intelligent devices.', 'hollywood helps little in this regard by fusing robots and advanced software into self-replicating automatons such as the terminator’s skynet or the evil hal seen in arthur clarke’s “2001: a space odyssey,” which goes rogue after humans plan to deactivate it.', 'the lack of clarity around the term enables technology pessimists to warn ai will conquer humans, suppress individual freedom, and destroy personal privacy through a digital “1984.”part of the problem is the lack of a uniformly agreed upon definition.',

In [8]:
from nltk.tokenize import sent_tokenize,word_tokenize
import regex
import string
def remove_punctuation(sentences):
  sent_list=[]
  for sent in sentences:
    words=word_tokenize(sent)
    str=""
    for i in range(len(words)):
      x=regex.sub("[^\w\s]|_","",words[i]).strip()
      str=str+" "+x
      str=str.strip()
    sent_list.append(str)
  return sent_list

sentences=remove_punctuation(sentences)
print(sentences)

['this report is part of a blueprint for the future of ai a series from the brookings institution that analyzes the new challenges and potential policy solutions introduced by artificial intelligence and other emerging technologiesfew concepts are as poorly understood as artificial intelligence', 'opinion surveys show that even top business leaders lack a detailed sense of ai and that many ordinary people confuse it with superpowered robots or hyperintelligent devices', 'hollywood helps little in this regard by fusing robots and advanced software into selfreplicating automatons such as the terminator s skynet or the evil hal seen in arthur clarke s 2001 a space odyssey which goes rogue after humans plan to deactivate it', 'the lack of clarity around the term enables technology pessimists to warn ai will conquer humans suppress individual freedom and destroy personal privacy through a digital 1984 part of the problem is the lack of a uniformly agreed upon definition', 'alan turing gener

In [9]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
def remove_stopwords(sentences):
  stop_words=set(stopwords.words("english"))
   
  sent_list=[]
  for sent in sentences:
    words=word_tokenize(sent)
    words=[word for word in words if word not in stop_words]
    words=" ".join(words)
    words=words.strip()
    sent_list.append(words)
  return sent_list

sentences=remove_stopwords(sentences)
print(sentences)

['report part blueprint future ai series brookings institution analyzes new challenges potential policy solutions introduced artificial intelligence emerging technologiesfew concepts poorly understood artificial intelligence', 'opinion surveys show even top business leaders lack detailed sense ai many ordinary people confuse superpowered robots hyperintelligent devices', 'hollywood helps little regard fusing robots advanced software selfreplicating automatons terminator skynet evil hal seen arthur clarke 2001 space odyssey goes rogue humans plan deactivate', 'lack clarity around term enables technology pessimists warn ai conquer humans suppress individual freedom destroy personal privacy digital 1984 part problem lack uniformly agreed upon definition', 'alan turing generally credited origin concept speculated 1950 thinking machines could reason level human', 'wellknown turing test specifies computers need complete reasoning puzzles well humans order considered thinking autonomous manne

In [10]:
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

def remove_stemming(sentences):
  stemmer=PorterStemmer()
  sent_list=[]
  for sent in sentences:
    words=word_tokenize(sent)
    words=[stemmer.stem(word) for word in words]
    words=" ".join(words)
    sent_list.append(words)
  return sent_list

sentences=remove_stemming(sentences)
print(sentences)

['report part blueprint futur ai seri brook institut analyz new challeng potenti polici solut introduc artifici intellig emerg technologiesfew concept poorli understood artifici intellig', 'opinion survey show even top busi leader lack detail sens ai mani ordinari peopl confus superpow robot hyperintellig devic', 'hollywood help littl regard fuse robot advanc softwar selfrepl automaton termin skynet evil hal seen arthur clark 2001 space odyssey goe rogu human plan deactiv', 'lack clariti around term enabl technolog pessimist warn ai conquer human suppress individu freedom destroy person privaci digit 1984 part problem lack uniformli agre upon definit', 'alan ture gener credit origin concept specul 1950 think machin could reason level human', 'wellknown ture test specifi comput need complet reason puzzl well human order consid think autonom mannertur follow year later john mccarthi first use term artifici intellig denot machin could think autonom', 'describ threshold get comput thing do

In [11]:
from nltk.tokenize import word_tokenize

def senetence_information(sentences):
  sent_info=[]
  for i,sent in enumerate(sentences):
    words=word_tokenize(sent)
    sent_dict={"sent_id":i,"sent_word_count":len(words)}
    sent_info.append(sent_dict)
    
  return sent_info
    
sent_info=senetence_information(sentences)
print(sent_info)

[{'sent_id': 0, 'sent_word_count': 24}, {'sent_id': 1, 'sent_word_count': 19}, {'sent_id': 2, 'sent_word_count': 25}, {'sent_id': 3, 'sent_word_count': 26}, {'sent_id': 4, 'sent_word_count': 14}, {'sent_id': 5, 'sent_word_count': 31}, {'sent_id': 6, 'sent_word_count': 22}, {'sent_id': 7, 'sent_word_count': 71}, {'sent_id': 8, 'sent_word_count': 27}, {'sent_id': 9, 'sent_word_count': 8}, {'sent_id': 10, 'sent_word_count': 20}, {'sent_id': 11, 'sent_word_count': 7}, {'sent_id': 12, 'sent_word_count': 18}, {'sent_id': 13, 'sent_word_count': 13}, {'sent_id': 14, 'sent_word_count': 13}, {'sent_id': 15, 'sent_word_count': 20}, {'sent_id': 16, 'sent_word_count': 17}, {'sent_id': 17, 'sent_word_count': 23}, {'sent_id': 18, 'sent_word_count': 13}, {'sent_id': 19, 'sent_word_count': 18}, {'sent_id': 20, 'sent_word_count': 21}, {'sent_id': 21, 'sent_word_count': 11}, {'sent_id': 22, 'sent_word_count': 25}, {'sent_id': 23, 'sent_word_count': 7}, {'sent_id': 24, 'sent_word_count': 21}, {'sent_id': 

In [12]:
from nltk.tokenize import word_tokenize
import matplotlib.pyplot as plt
def frequency_of_words(sentences):
  freq_info=[]
  for i,sent in enumerate(sentences):
    words=word_tokenize(sent)
    frequency_dict={}
    for word in words:
      if word in frequency_dict.keys():
        frequency_dict[word]=frequency_dict[word]+1
      else:
        frequency_dict[word]=1
    temp={"sent_id":i,"frequency_of_word":frequency_dict}
    freq_info.append(temp)
    
  return freq_info

freq_info=frequency_of_words(sentences)



In [13]:
def unik_word(sentences):
  unik=[]
  for sents in sentences:
    for word in word_tokenize(sents):
      if word not in unik:
        unik.append(word)
  return unik
unik_words=unik_word(sentences)
print(len(unik_words))

542


**TF-IDF CALCULATION**

In [14]:
import numpy as np

def tf_calculation(sent_info,freq_info):
  tf_values=np.zeros(shape=(len(sent_info),len(unik_words)))
  for i,freq_info_dict in enumerate(freq_info):
    for word in freq_info_dict["frequency_of_word"].keys():
      tf=freq_info_dict["frequency_of_word"][word]/sent_info[i]["sent_word_count"]
      tf_values[i][unik_words.index(word)]=tf
  return tf_values
   
  
tf_values=tf_calculation(sent_info,freq_info)
print(tf_values)

[[0.04166667 0.04166667 0.04166667 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.04545455 0.04545455 0.04545455]]


In [15]:
import math

def idf_calculate(sent_info,freq_info):
  idf_values=np.zeros(shape=(len(sent_info),len(unik_words)))
  for i,freq_info_dict in enumerate(freq_info):
    for word in freq_info_dict["frequency_of_word"].keys():
      sum=0
      for word_in_dict in freq_info:
        if word in set(word_in_dict["frequency_of_word"].keys()):
          sum=sum+word_in_dict["frequency_of_word"][word]
      idf_values[i][unik_words.index(word)]=math.log(len(sentences)/sum)
  return idf_values
        
idf_values=idf_calculate(sent_info,freq_info)
print(idf_values)

[[4.00733319 3.314186   4.00733319 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 4.00733319 4.00733319 4.00733319]]


In [16]:
import numpy as np

def tfidf_calculation(tf_values,idf_values):
  tfidf_values=np.zeros(shape=(len(sent_info),len(unik_words)))
  tfidf_values=np.multiply(tf_values,idf_values)
  return tfidf_values

tfidf_values=tfidf_calculation(tf_values,idf_values)
print(tfidf_values)

[[0.16697222 0.13809108 0.16697222 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.18215151 0.18215151 0.18215151]]


**COSINE SIMILARITY MATRIX**

In [17]:
import numpy as np
import math

def cosine_similarity(sent_1,sent_2):
  s1_dot_s2=np.sum(np.multiply(sent_1,sent_2))
  magnitude_of_s1=math.sqrt(np.sum(np.multiply(sent_1,sent_1)))
  magnitude_of_s2=math.sqrt(np.sum(np.multiply(sent_2,sent_2)))
  return s1_dot_s2/(magnitude_of_s1*magnitude_of_s2)

In [18]:
import numpy as np

def cosine_matrix(tfidf_values):
  cosine_similarity_matrix=np.zeros(shape=(len(sentences),len(sentences)))
  for i in range(len(tfidf_values)):
    for j in range(len(tfidf_values)):
      cosine_similarity_matrix[i][j]=cosine_similarity(tfidf_values[i],tfidf_values[j])
  #normalize the matrix
  for idx in range(len(cosine_similarity_matrix)):
    cosine_similarity_matrix[idx] /= cosine_similarity_matrix[idx].sum()
    
  return cosine_similarity_matrix

cosine_similarity_matrix=cosine_matrix(tfidf_values)
print(cosine_similarity_matrix)

[[0.48958698 0.00106811 0.         ... 0.00169921 0.01694288 0.0696266 ]
 [0.00159317 0.73025258 0.02181526 ... 0.0026259  0.02498792 0.        ]
 [0.         0.01897597 0.63520927 ... 0.         0.00530707 0.        ]
 ...
 [0.0020108  0.00208333 0.         ... 0.57936402 0.04119378 0.01047033]
 [0.01425676 0.01409679 0.00344193 ... 0.02929163 0.41196787 0.00238276]
 [0.05801158 0.         0.         ... 0.00737188 0.00235932 0.4079147 ]]


**TEXT RANK ALGORITHM**

In [19]:
import numpy as np
def text_rank(cosine_matrix,eps=0.0001,d=0.85):
  teleportation_factor=np.ones(len(sentences))/len(sentences)
  i=0
  while i<100:
    new_p=np.dot(cosine_similarity_matrix.T,teleportation_factor.T)
    if i<=100:
      return new_p
    i=i+1
    teleportation_factor = new_p
  
  
result_rank=text_rank(cosine_similarity_matrix)
print(len(sentences))
rank_with_sentence={}
for i in range(len(sent_for_print)):
  if result_rank[i] not in set(rank_with_sentence.keys()):
    rank_with_sentence[result_rank[i]]=[sent_for_print[i]]
  else:
    rank_with_sentence[result_rank[i]].append(sent_for_print[i])
    

#sentences with their rank
for key in sorted(rank_with_sentence.keys(),reverse=True)[:int(len(rank_with_sentence.keys())/4)]:
  for k in rank_with_sentence[key]:
    #print(key,k)
    k[0].upper()
    print(k)
    

55
situations where ai-powered robots take over from humans or weaken basic values frighten people and lead them to wonder whether ai is making a useful contribution or runs the risk of endangering the essence of humanity.with the appropriate safeguards, countries can move forward and gain the benefits of artificial intelligence and emerging technologies without sacrificing the important qualities that define humanity.there is no easy answer to that question, but system designers must incorporate important ethical values in algorithms to make sure they correspond to human concerns and learn and adapt in ways that are consistent with community values.
advanced computers such as the ibm watson already have beaten humans at chess and are capable of instantly processing enormous amounts of information.the lack of clarity around the term enables technology pessimists to warn ai will conquer humans, suppress individual freedom, and destroy personal privacy through a digital “1984.”today, ai 